[[repos]]
repo = "local"

[[repos.hooks]]
id = "statix"
name = "Lint Nix files"
language = "system"
entry = "statix check"
files = '\.nix$'
pass_filenames = false

[[repos.hooks]]
id = "deadnix"
name = "Find dead Nix code"
language = "system"
entry = "deadnix --fail"
files = '\.nix$'

[[repos.hooks]]
id = "alejandra"
name = "Format Nix files"
language = "system"
entry = "alejandra"
files = '\.nix$'

[[repos.hooks]]
id = "nix-build-dry-run"
name = "Check packages evaluate"
language = "system"
entry = "nix flake check --no-build"
pass_filenames = false

[[repos.hooks]]
id = "shellcheck"
name = "Lint shell scripts"
language = "system"
entry = "shellcheck"
files = '\.sh$'
