{
  lib,
  buildNpmPackage,
  fetchNpmDeps,
  bun,
  version,
  src,
}:
buildNpmPackage {
  pname = "pounce-cli";
  inherit version src;

  # The repo tag, not apps/cli's own 0.6.0 — the point of this package is that
  # the CLI and the desktop app move together. `pounce --help` still prints the
  # upstream number.
  sourceRoot = "${src.name}/apps/cli";

  # apps/cli ships no lockfile: it is a bun workspace member and resolves
  # through the repo-root bun.lock. cli-npm/ is that member's dependency closure
  # re-resolved with npm, regenerated by update.nu.
  #
  # It also carries two dependencies the published package does not declare.
  # scripts/build.mjs keeps only the packages in its EXTERNAL list external, so
  # agent-canonical and node-machine-id get inlined into dist/launcher.mjs and
  # have to be resolvable while bun bundles.
  #
  # `install`, not `cp`: npmConfigHook rewrites the lockfile in place with
  # --fixup-lockfile, and a 0444 copy out of the store leaves it truncated.
  postPatch = ''
    install -m644 ${./cli-npm/package.json} package.json
    install -m644 ${./cli-npm/package-lock.json} package-lock.json

    # npm walks up to the nearest manifest declaring `workspaces`, decides the
    # repo root is the project, and then rejects `npm ci` for having no lockfile
    # there. Nothing in this build reads the root manifest, so drop it — only
    # sourceRoot comes back writable from the store, hence the chmod.
    chmod u+w ../..
    rm ../../package.json
  '';

  npmDeps = fetchNpmDeps {
    name = "pounce-cli-npm-deps";
    src = ./cli-npm;
    hash = "sha256-Y9Zs/67c93hOvysZauxuR/soiZyEEbRvLEnHcfQXk7E=";
  };

  nativeBuildInputs = [bun];

  # `bun build` inlines the workspace-private bridge, and those files import
  # node-machine-id and @pounce/transcript. Resolution walks up from
  # apps/bridge/, which never reaches apps/cli/node_modules — so the repo root
  # gets one pointing at it, and the workspace package gets an entry inside.
  preBuild = ''
    mkdir -p node_modules/@pounce
    ln -s ../../../../packages/transcript node_modules/@pounce/transcript
    ln -s "$PWD/node_modules" ../../node_modules
  '';

  # prepack is the same `bun scripts/build.mjs` the build phase just ran.
  npmPackFlags = ["--ignore-scripts"];

  # packages/pounce/update.nu drives version and every hash here; nix-update
  # pointed at pounce-cli would only find a version it must not move alone.
  passthru.updatePolicy = "skip";

  meta = {
    description = "Pair your phone with this machine in one command and run the Pounce bridge";
    homepage = "https://use-pounce.com";
    license = lib.licenses.mit;
    maintainers = [];
    mainProgram = "pounce";
  };
}
